"""Added cloud_cost table

Revision ID: 1c03779bf3a3
Revises: 
Create Date: 2025-02-28 08:16:38.768331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c03779bf3a3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_cost_id'), 'cloud_cost', ['id'], unique=False)
    op.alter_column('recommendations', 'command',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('recommendations', 'savings',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('recommendations', 'applied',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('recommendations', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recommendations', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('recommendations', 'applied',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('recommendations', 'savings',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('recommendations', 'command',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_cloud_cost_id'), table_name='cloud_cost')
    op.drop_table('cloud_cost')
    # ### end Alembic commands ###
