"""initial schema

Revision ID: 48aea061b482
Revises: 
Create Date: 2025-03-10 20:53:49.904436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48aea061b482'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('tag_key', sa.String(), nullable=True),
    sa.Column('tag_value', sa.String(), nullable=True),
    sa.Column('time_period', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('threshold_percentage', sa.Float(), nullable=False),
    sa.Column('current_usage', sa.Float(), nullable=True),
    sa.Column('last_evaluated', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('email_recipients', sa.JSON(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_alerts_account_id'), 'budget_alerts', ['account_id'], unique=False)
    op.create_index(op.f('ix_budget_alerts_id'), 'budget_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_budget_alerts_provider'), 'budget_alerts', ['provider'], unique=False)
    op.create_index(op.f('ix_budget_alerts_service'), 'budget_alerts', ['service'], unique=False)
    op.create_index(op.f('ix_budget_alerts_status'), 'budget_alerts', ['status'], unique=False)
    op.create_table('cloud_cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('extra_data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_cost_id'), 'cloud_cost', ['id'], unique=False)
    op.create_table('cloud_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_resources_account_id'), 'cloud_resources', ['account_id'], unique=False)
    op.create_index(op.f('ix_cloud_resources_id'), 'cloud_resources', ['id'], unique=False)
    op.create_index(op.f('ix_cloud_resources_name'), 'cloud_resources', ['name'], unique=False)
    op.create_index(op.f('ix_cloud_resources_provider'), 'cloud_resources', ['provider'], unique=False)
    op.create_index(op.f('ix_cloud_resources_region'), 'cloud_resources', ['region'], unique=False)
    op.create_index(op.f('ix_cloud_resources_resource_id'), 'cloud_resources', ['resource_id'], unique=True)
    op.create_index(op.f('ix_cloud_resources_resource_type'), 'cloud_resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_cloud_resources_service'), 'cloud_resources', ['service'], unique=False)
    op.create_index(op.f('ix_cloud_resources_status'), 'cloud_resources', ['status'], unique=False)
    op.create_table('cost_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('allocation_method', sa.String(), nullable=False),
    sa.Column('allocated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_allocation_date_service', 'cost_allocations', ['date', 'service'], unique=False)
    op.create_index('idx_allocation_entity_date', 'cost_allocations', ['entity_type', 'entity_id', 'date'], unique=False)
    op.create_index(op.f('ix_cost_allocations_date'), 'cost_allocations', ['date'], unique=False)
    op.create_index(op.f('ix_cost_allocations_entity_id'), 'cost_allocations', ['entity_id'], unique=False)
    op.create_index(op.f('ix_cost_allocations_entity_name'), 'cost_allocations', ['entity_name'], unique=False)
    op.create_index(op.f('ix_cost_allocations_entity_type'), 'cost_allocations', ['entity_type'], unique=False)
    op.create_index(op.f('ix_cost_allocations_id'), 'cost_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_cost_allocations_provider'), 'cost_allocations', ['provider'], unique=False)
    op.create_index(op.f('ix_cost_allocations_service'), 'cost_allocations', ['service'], unique=False)
    op.create_table('cost_anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('baseline_cost', sa.Float(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('detection_method', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('root_cause', sa.JSON(), nullable=True),
    sa.Column('cloud_context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_anomalies_created_at'), 'cost_anomalies', ['created_at'], unique=False)
    op.create_index(op.f('ix_cost_anomalies_date'), 'cost_anomalies', ['date'], unique=False)
    op.create_index(op.f('ix_cost_anomalies_id'), 'cost_anomalies', ['id'], unique=False)
    op.create_index(op.f('ix_cost_anomalies_provider'), 'cost_anomalies', ['provider'], unique=False)
    op.create_index(op.f('ix_cost_anomalies_resource_id'), 'cost_anomalies', ['resource_id'], unique=False)
    op.create_index(op.f('ix_cost_anomalies_service'), 'cost_anomalies', ['service'], unique=False)
    op.create_index(op.f('ix_cost_anomalies_status'), 'cost_anomalies', ['status'], unique=False)
    op.create_table('cost_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_categories_id'), 'cost_categories', ['id'], unique=False)
    op.create_index(op.f('ix_cost_categories_name'), 'cost_categories', ['name'], unique=False)
    op.create_table('cost_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('target_date', sa.String(), nullable=False),
    sa.Column('predicted_cost', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('algorithm', sa.String(), nullable=True),
    sa.Column('data_points_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_forecasts_created_at'), 'cost_forecasts', ['created_at'], unique=False)
    op.create_index(op.f('ix_cost_forecasts_id'), 'cost_forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_cost_forecasts_provider'), 'cost_forecasts', ['provider'], unique=False)
    op.create_index(op.f('ix_cost_forecasts_service'), 'cost_forecasts', ['service'], unique=False)
    op.create_index(op.f('ix_cost_forecasts_target_date'), 'cost_forecasts', ['target_date'], unique=False)
    op.create_table('optimization_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('is_automatic', sa.Boolean(), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_policies_enabled'), 'optimization_policies', ['enabled'], unique=False)
    op.create_index(op.f('ix_optimization_policies_id'), 'optimization_policies', ['id'], unique=False)
    op.create_index(op.f('ix_optimization_policies_name'), 'optimization_policies', ['name'], unique=False)
    op.create_index(op.f('ix_optimization_policies_provider'), 'optimization_policies', ['provider'], unique=False)
    op.create_index(op.f('ix_optimization_policies_resource_type'), 'optimization_policies', ['resource_type'], unique=False)
    op.create_index(op.f('ix_optimization_policies_service'), 'optimization_policies', ['service'], unique=False)
    op.create_table('organization_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('account_ids', sa.JSON(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['organization_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_units_external_id'), 'organization_units', ['external_id'], unique=False)
    op.create_index(op.f('ix_organization_units_id'), 'organization_units', ['id'], unique=False)
    op.create_index(op.f('ix_organization_units_name'), 'organization_units', ['name'], unique=False)
    op.create_index(op.f('ix_organization_units_parent_id'), 'organization_units', ['parent_id'], unique=False)
    op.create_index(op.f('ix_organization_units_path'), 'organization_units', ['path'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('suggestion', sa.String(), nullable=False),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('savings', sa.Float(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_table('resource_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tag_key_value', 'resource_tags', ['key', 'value'], unique=True)
    op.create_index(op.f('ix_resource_tags_id'), 'resource_tags', ['id'], unique=False)
    op.create_index(op.f('ix_resource_tags_key'), 'resource_tags', ['key'], unique=False)
    op.create_index(op.f('ix_resource_tags_value'), 'resource_tags', ['value'], unique=False)
    op.create_table('resource_utilizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sa.String(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('statistic', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_utilization_resource_metric_date', 'resource_utilizations', ['resource_id', 'metric_name', 'date'], unique=False)
    op.create_index('idx_utilization_service_metric_date', 'resource_utilizations', ['service', 'metric_name', 'date'], unique=False)
    op.create_index(op.f('ix_resource_utilizations_date'), 'resource_utilizations', ['date'], unique=False)
    op.create_index(op.f('ix_resource_utilizations_id'), 'resource_utilizations', ['id'], unique=False)
    op.create_index(op.f('ix_resource_utilizations_metric_name'), 'resource_utilizations', ['metric_name'], unique=False)
    op.create_index(op.f('ix_resource_utilizations_provider'), 'resource_utilizations', ['provider'], unique=False)
    op.create_index(op.f('ix_resource_utilizations_resource_id'), 'resource_utilizations', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_utilizations_service'), 'resource_utilizations', ['service'], unique=False)
    op.create_index(op.f('ix_resource_utilizations_timestamp'), 'resource_utilizations', ['timestamp'], unique=False)
    op.create_table('saved_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('grouping', sa.JSON(), nullable=True),
    sa.Column('time_range', sa.JSON(), nullable=True),
    sa.Column('visualization', sa.JSON(), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=True),
    sa.Column('schedule', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_reports_id'), 'saved_reports', ['id'], unique=False)
    op.create_index(op.f('ix_saved_reports_name'), 'saved_reports', ['name'], unique=False)
    op.create_index(op.f('ix_saved_reports_report_type'), 'saved_reports', ['report_type'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=True),
    sa.Column('anomaly_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['cost_anomalies.id'], ),
    sa.ForeignKeyConstraint(['budget_id'], ['budget_alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_history_acknowledged'), 'alert_history', ['acknowledged'], unique=False)
    op.create_index(op.f('ix_alert_history_alert_type'), 'alert_history', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alert_history_anomaly_id'), 'alert_history', ['anomaly_id'], unique=False)
    op.create_index(op.f('ix_alert_history_budget_id'), 'alert_history', ['budget_id'], unique=False)
    op.create_index(op.f('ix_alert_history_created_at'), 'alert_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_alert_history_id'), 'alert_history', ['id'], unique=False)
    op.create_index(op.f('ix_alert_history_severity'), 'alert_history', ['severity'], unique=False)
    op.create_table('resource_tag_association',
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['cloud_resources.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['resource_tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_tag_association')
    op.drop_index(op.f('ix_alert_history_severity'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_created_at'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_budget_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_anomaly_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_alert_type'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_acknowledged'), table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index(op.f('ix_saved_reports_report_type'), table_name='saved_reports')
    op.drop_index(op.f('ix_saved_reports_name'), table_name='saved_reports')
    op.drop_index(op.f('ix_saved_reports_id'), table_name='saved_reports')
    op.drop_table('saved_reports')
    op.drop_index(op.f('ix_resource_utilizations_timestamp'), table_name='resource_utilizations')
    op.drop_index(op.f('ix_resource_utilizations_service'), table_name='resource_utilizations')
    op.drop_index(op.f('ix_resource_utilizations_resource_id'), table_name='resource_utilizations')
    op.drop_index(op.f('ix_resource_utilizations_provider'), table_name='resource_utilizations')
    op.drop_index(op.f('ix_resource_utilizations_metric_name'), table_name='resource_utilizations')
    op.drop_index(op.f('ix_resource_utilizations_id'), table_name='resource_utilizations')
    op.drop_index(op.f('ix_resource_utilizations_date'), table_name='resource_utilizations')
    op.drop_index('idx_utilization_service_metric_date', table_name='resource_utilizations')
    op.drop_index('idx_utilization_resource_metric_date', table_name='resource_utilizations')
    op.drop_table('resource_utilizations')
    op.drop_index(op.f('ix_resource_tags_value'), table_name='resource_tags')
    op.drop_index(op.f('ix_resource_tags_key'), table_name='resource_tags')
    op.drop_index(op.f('ix_resource_tags_id'), table_name='resource_tags')
    op.drop_index('idx_tag_key_value', table_name='resource_tags')
    op.drop_table('resource_tags')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_organization_units_path'), table_name='organization_units')
    op.drop_index(op.f('ix_organization_units_parent_id'), table_name='organization_units')
    op.drop_index(op.f('ix_organization_units_name'), table_name='organization_units')
    op.drop_index(op.f('ix_organization_units_id'), table_name='organization_units')
    op.drop_index(op.f('ix_organization_units_external_id'), table_name='organization_units')
    op.drop_table('organization_units')
    op.drop_index(op.f('ix_optimization_policies_service'), table_name='optimization_policies')
    op.drop_index(op.f('ix_optimization_policies_resource_type'), table_name='optimization_policies')
    op.drop_index(op.f('ix_optimization_policies_provider'), table_name='optimization_policies')
    op.drop_index(op.f('ix_optimization_policies_name'), table_name='optimization_policies')
    op.drop_index(op.f('ix_optimization_policies_id'), table_name='optimization_policies')
    op.drop_index(op.f('ix_optimization_policies_enabled'), table_name='optimization_policies')
    op.drop_table('optimization_policies')
    op.drop_index(op.f('ix_cost_forecasts_target_date'), table_name='cost_forecasts')
    op.drop_index(op.f('ix_cost_forecasts_service'), table_name='cost_forecasts')
    op.drop_index(op.f('ix_cost_forecasts_provider'), table_name='cost_forecasts')
    op.drop_index(op.f('ix_cost_forecasts_id'), table_name='cost_forecasts')
    op.drop_index(op.f('ix_cost_forecasts_created_at'), table_name='cost_forecasts')
    op.drop_table('cost_forecasts')
    op.drop_index(op.f('ix_cost_categories_name'), table_name='cost_categories')
    op.drop_index(op.f('ix_cost_categories_id'), table_name='cost_categories')
    op.drop_table('cost_categories')
    op.drop_index(op.f('ix_cost_anomalies_status'), table_name='cost_anomalies')
    op.drop_index(op.f('ix_cost_anomalies_service'), table_name='cost_anomalies')
    op.drop_index(op.f('ix_cost_anomalies_resource_id'), table_name='cost_anomalies')
    op.drop_index(op.f('ix_cost_anomalies_provider'), table_name='cost_anomalies')
    op.drop_index(op.f('ix_cost_anomalies_id'), table_name='cost_anomalies')
    op.drop_index(op.f('ix_cost_anomalies_date'), table_name='cost_anomalies')
    op.drop_index(op.f('ix_cost_anomalies_created_at'), table_name='cost_anomalies')
    op.drop_table('cost_anomalies')
    op.drop_index(op.f('ix_cost_allocations_service'), table_name='cost_allocations')
    op.drop_index(op.f('ix_cost_allocations_provider'), table_name='cost_allocations')
    op.drop_index(op.f('ix_cost_allocations_id'), table_name='cost_allocations')
    op.drop_index(op.f('ix_cost_allocations_entity_type'), table_name='cost_allocations')
    op.drop_index(op.f('ix_cost_allocations_entity_name'), table_name='cost_allocations')
    op.drop_index(op.f('ix_cost_allocations_entity_id'), table_name='cost_allocations')
    op.drop_index(op.f('ix_cost_allocations_date'), table_name='cost_allocations')
    op.drop_index('idx_allocation_entity_date', table_name='cost_allocations')
    op.drop_index('idx_allocation_date_service', table_name='cost_allocations')
    op.drop_table('cost_allocations')
    op.drop_index(op.f('ix_cloud_resources_status'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_service'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_resource_type'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_resource_id'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_region'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_provider'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_name'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_id'), table_name='cloud_resources')
    op.drop_index(op.f('ix_cloud_resources_account_id'), table_name='cloud_resources')
    op.drop_table('cloud_resources')
    op.drop_index(op.f('ix_cloud_cost_id'), table_name='cloud_cost')
    op.drop_table('cloud_cost')
    op.drop_index(op.f('ix_budget_alerts_status'), table_name='budget_alerts')
    op.drop_index(op.f('ix_budget_alerts_service'), table_name='budget_alerts')
    op.drop_index(op.f('ix_budget_alerts_provider'), table_name='budget_alerts')
    op.drop_index(op.f('ix_budget_alerts_id'), table_name='budget_alerts')
    op.drop_index(op.f('ix_budget_alerts_account_id'), table_name='budget_alerts')
    op.drop_table('budget_alerts')
    # ### end Alembic commands ###
