"""add auth models

Revision ID: 97c35a042332
Revises: b23a9e53a5d6
Create Date: 2025-03-08 07:53:28.735743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '97c35a042332'
down_revision: Union[str, None] = 'b23a9e53a5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
     with op.batch_alter_table('alert_history') as batch_op:
        batch_op.alter_column('acknowledged',
                             existing_type=sa.BOOLEAN(),
                             nullable=True,
                             existing_server_default=sa.text("'0'"))
        op.drop_index('idx_cost_date_service', table_name='cloud_cost')
        op.drop_index('idx_cost_provider_date', table_name='cloud_cost')
        op.drop_index('idx_cost_resource_date', table_name='cloud_cost')
        op.drop_index('ix_cloud_cost_account_id', table_name='cloud_cost')
        op.drop_index('ix_cloud_cost_region', table_name='cloud_cost')
        op.drop_index('ix_cloud_cost_resource_id', table_name='cloud_cost')
        op.drop_column('cloud_cost', 'region')
        op.drop_column('cloud_cost', 'usage_quantity')
        op.drop_column('cloud_cost', 'resource_id')
        op.drop_column('cloud_cost', 'account_id')
        op.drop_column('cloud_cost', 'usage_unit')
        with op.batch_alter_table('optimization_policies') as batch_op:
            batch_op.alter_column('is_automatic',
                existing_type=sa.BOOLEAN(),
                nullable=True,
                existing_server_default=sa.text("'0'"))
        with op.batch_alter_table ('optimization_policies') as batch_op:
            batch_op.alter_column('approval_required',
                existing_type=sa.BOOLEAN(),
                nullable=True,
                existing_server_default=sa.text("'1'"))
        with op.batch_alter_table('optimization_policies') as batch_op:
            batch_op.alter_column('enabled',
                existing_type=sa.BOOLEAN(),
                nullable=True,
                existing_server_default=sa.text("'1'"))
        op.add_column('organization_units', sa.Column('meta_data', sa.JSON(), nullable=True))
        op.drop_column('organization_units', 'metadata')
        op.drop_index('ix_recommendations_category', table_name='recommendations')
        op.drop_index('ix_recommendations_rejected', table_name='recommendations')
        op.drop_column('recommendations', 'savings_percentage')
        op.drop_column('recommendations', 'applied_at')
        op.drop_column('recommendations', 'rejected_reason')
        op.drop_column('recommendations', 'title')
        op.drop_column('recommendations', 'rejected')
        op.drop_column('recommendations', 'confidence')
        op.drop_column('recommendations', 'effort')
        op.drop_column('recommendations', 'category')
        op.drop_column('recommendations', 'impact')
        op.drop_column('recommendations', 'actual_savings')
        op.drop_column('recommendations', 'effectiveness')
        op.drop_column('recommendations', 'resources')
        with op.batch_alter_table('saved_reports') as batch_op:
            batch_op.alter_column('is_scheduled',
                existing_type=sa.BOOLEAN(),
                nullable=True,
                existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saved_reports', 'is_scheduled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.add_column('recommendations', sa.Column('resources', sqlite.JSON(), nullable=True))
    op.add_column('recommendations', sa.Column('effectiveness', sa.FLOAT(), nullable=True))
    op.add_column('recommendations', sa.Column('actual_savings', sa.FLOAT(), nullable=True))
    op.add_column('recommendations', sa.Column('impact', sa.VARCHAR(), nullable=True))
    op.add_column('recommendations', sa.Column('category', sa.VARCHAR(), nullable=True))
    op.add_column('recommendations', sa.Column('effort', sa.VARCHAR(), nullable=True))
    op.add_column('recommendations', sa.Column('confidence', sa.VARCHAR(), nullable=True))
    op.add_column('recommendations', sa.Column('rejected', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
    op.add_column('recommendations', sa.Column('title', sa.VARCHAR(), nullable=True))
    op.add_column('recommendations', sa.Column('rejected_reason', sa.VARCHAR(), nullable=True))
    op.add_column('recommendations', sa.Column('applied_at', sa.DATETIME(), nullable=True))
    op.add_column('recommendations', sa.Column('savings_percentage', sa.FLOAT(), nullable=True))
    op.create_index('ix_recommendations_rejected', 'recommendations', ['rejected'], unique=False)
    op.create_index('ix_recommendations_category', 'recommendations', ['category'], unique=False)
    op.add_column('organization_units', sa.Column('metadata', sqlite.JSON(), nullable=True))
    op.drop_column('organization_units', 'meta_data')
    op.alter_column('optimization_policies', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('optimization_policies', 'approval_required',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('optimization_policies', 'is_automatic',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.add_column('cloud_cost', sa.Column('usage_unit', sa.VARCHAR(), nullable=True))
    op.add_column('cloud_cost', sa.Column('account_id', sa.VARCHAR(), nullable=True))
    op.add_column('cloud_cost', sa.Column('resource_id', sa.VARCHAR(), nullable=True))
    op.add_column('cloud_cost', sa.Column('usage_quantity', sa.FLOAT(), nullable=True))
    op.add_column('cloud_cost', sa.Column('region', sa.VARCHAR(), nullable=True))
    op.create_index('ix_cloud_cost_resource_id', 'cloud_cost', ['resource_id'], unique=False)
    op.create_index('ix_cloud_cost_region', 'cloud_cost', ['region'], unique=False)
    op.create_index('ix_cloud_cost_account_id', 'cloud_cost', ['account_id'], unique=False)
    op.create_index('idx_cost_resource_date', 'cloud_cost', ['resource_id', 'date'], unique=False)
    op.create_index('idx_cost_provider_date', 'cloud_cost', ['provider', 'date'], unique=False)
    op.create_index('idx_cost_date_service', 'cloud_cost', ['date', 'service'], unique=False)
    op.alter_column('alert_history', 'acknowledged',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###
